import { FoodItem, MenuCategory } from './types';

export const categories: MenuCategory[] = [
  { id: 'all', name: 'All', nameTa: 'அனைத்தும்', icon: 'Utensils' },
  { id: 'breakfast', name: 'Breakfast', nameTa: 'காலை உணவு', icon: 'Sun' },
  { id: 'mains', name: 'Mains', nameTa: 'முக்கிய உணவு', icon: 'Flame' },
  { id: 'veg', name: 'Vegetarian', nameTa: 'சைவம்', icon: 'Leaf' },
  { id: 'beverages', name: 'Beverages', nameTa: 'பானங்கள்', icon: 'Coffee' },
  { id: 'desserts', name: 'Desserts', nameTa: 'இனிப்புகள்', icon: 'IceCream' },
];

export const foodItems: FoodItem[] = [
  {
    id: 'food_1',
    name: 'Ghee Podi Masala Dosa',
    nameTa: 'நெய் பொடி மசாலா தோசை',
    category: 'breakfast',
    price: 140,
    description: 'Crispy rice crepe roasted with pure cow ghee, spiced lentil powder (podi), and stuffed with seasoned potato masala.',
    descriptionTa: 'சுவையான நெய் மற்றும் காரசாரமான இட்லி பொடி தூவி, உருளைக்கிழங்கு மசாலா வைத்து சுடச்சுட வழங்கப்படும் மொறுமொறுப்பான தோசை.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    prepTime: 10,
    isVeg: true,
    isBestSeller: true,
    extras: [
      { name: 'Extra Potato Masala', nameTa: 'கூடுதல் உருளைக் கிழங்கு மசாலா', price: 20 },
      { name: 'Extra Podi', nameTa: 'கூடுதல் இட்லி பொடி', price: 10 },
      { name: 'Ghee Topping', nameTa: 'கூடுதல் நெய்', price: 25 },
    ],
  },
  {
    id: 'food_2',
    name: 'Royal Ambur Chicken Biryani',
    nameTa: 'ஆம்பூர் சிக்கன் பிரியாணி',
    category: 'mains',
    price: 280,
    description: 'Traditional wood-fired aromatic Seeraga Samba rice cooked with tender chicken, curd, and hand-ground spices in traditional Ambur style.',
    descriptionTa: 'பாரம்பரிய சீரக சம்பா அரிசி கொண்டு, சிறந்த நறுமண மசாலாப் பொருட்களுடன், விறகு அடுப்பில் சமைக்கப்பட்ட சுவையான ஆம்பூர் பிரியாணி.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    prepTime: 15,
    isVeg: false,
    isBestSeller: true,
    extras: [
      { name: 'Extra Chicken Piece', nameTa: 'கூடுதல் சிக்கன் துண்டு', price: 60 },
      { name: 'Boiled Egg', nameTa: 'அவித்த முட்டை', price: 15 },
      { name: 'Extra Salna & Raita', nameTa: 'கூடுதல் சால்னா மற்றும் தயிர் பச்சடி', price: 0 },
    ],
  },
  {
    id: 'food_3',
    name: 'Madurai Malligai Poo Idli (3 Pcs)',
    nameTa: 'மதுரை மல்லிகைப்பூ இட்லி (3 துண்டுகள்)',
    category: 'breakfast',
    price: 80,
    description: 'Super soft, feather-light steamed rice cakes shaped like jasmine flowers, served with 3 varieties of chutneys and hot sambar.',
    descriptionTa: 'மதுரைக்கே உரித்தான, மல்லிகைப் பூவைப் போன்ற மென்மையான இட்லி, மூன்று வகையான துவையல் மற்றும் சூடான சாம்பாருடன் வழங்கப்படும்.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    prepTime: 8,
    isVeg: true,
    extras: [
      { name: 'Extra Sambar Bowl', nameTa: 'சூடான சாம்பார் கிண்ணம்', price: 15 },
      { name: 'Vada (1 Pc)', nameTa: 'மெதுவடை (1 துண்டு)', price: 20 },
    ],
  },
  {
    id: 'food_4',
    name: 'Kumbakonam Degree Filter Coffee',
    nameTa: 'கும்பகோணம் டிகிரி ஃபில்டர் காபி',
    category: 'beverages',
    price: 50,
    description: 'Authentic South Indian chicory-blend coffee extracted using a brass filter and thoroughly frothed with rich buffalo milk.',
    descriptionTa: 'செப்பு வடிகட்டியில் இறக்கிய காபி டிகாக்ஷன் மற்றும் திக்கான பால் சேர்த்து, பாரம்பரிய முறைப்படி நுரை பொங்க ஆற்றி வழங்கப்படும் நல்ல நறுமண காபி.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    prepTime: 5,
    isVeg: true,
    isBestSeller: true,
  },
  {
    id: 'food_5',
    name: 'Paneer Butter Masala',
    nameTa: 'பனீர் பட்டர் மசாலா',
    category: 'veg',
    price: 210,
    description: 'Fresh cubed cottage cheese simmered in a creamy, velvety tomato gravy enriched with butter, cashew paste, and dried fenugreek leaves.',
    descriptionTa: 'மென்மையான பனீர் துண்டுகள், இனிப்பு கலந்த தக்காளி சாந்து, வெண்ணெய், முந்திரி விழுது சேர்த்து சமைக்கப்பட்ட வட இந்திய சைவம்.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    prepTime: 12,
    isVeg: true,
    extras: [
      { name: 'Extra Butter/Cream', nameTa: 'கூடுதல் வெண்ணெய்', price: 20 },
      { name: 'More Paneer Cubes', nameTa: 'கூடுதல் பனீர்', price: 40 },
    ],
  },
  {
    id: 'food_6',
    name: 'Tandoori Garlic Naan (2 Pcs)',
    nameTa: 'பூண்டு நாண் (2 துண்டுகள்)',
    category: 'mains',
    price: 90,
    description: 'Soft flatbread clay-baked in a tandoor, brushed liberally with melted butter and infused with toasted chopped garlic.',
    descriptionTa: 'தந்தூரி அடுப்பில் சுடப்பட்டு, வெண்ணெய் மற்றும் நறுக்கிய பூண்டு தூவி வழங்கப்படும் ருசியான மென்மையான பூண்டு நாண்.',
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    prepTime: 10,
    isVeg: true,
    extras: [
      { name: 'Extra Butter Spread', nameTa: 'வெண்ணெய் தடவப்பட்டது', price: 15 },
    ],
  },
  {
    id: 'food_7',
    name: 'Alphonso Mango Lassi',
    nameTa: 'அல்போன்சா மாம்பழ லஸ்ஸி',
    category: 'beverages',
    price: 110,
    description: 'Chilled creamy yogurt blended with sweet natural Alphonso mango pulp, garnished with cardamoms and pistachio slivers.',
    descriptionTa: 'தயிர் மற்றும் மதுரமான அல்போன்சா மாம்பழ விழுது கலந்து, ஏலக்காய் மற்றும் பருப்புகள் தூவி வழங்கப்படும் குளிர்ச்சியான பானம்.',
    image: 'https://images.unsplash.com/photo-1571006682855-3914a87ef871?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    prepTime: 5,
    isVeg: true,
  },
  {
    id: 'food_8',
    name: 'Saffron Elaneer Payasam',
    nameTa: 'குங்குமப்பூ இளநீர் பாயசம்',
    category: 'desserts',
    price: 130,
    description: 'A delicate dessert made of tender coconut kernel pulp, chilled coconut milk, and sweetened condensed milk flavored with premium high-grade saffron.',
    descriptionTa: 'இளநீர் வழுக்கை மற்றும் தேங்காய்ப் பால் கொண்டு தயாரிக்கப்பட்டு குங்குமப்பூ வாசனை ஊட்டப்பட்ட விசேஷமான தென் இந்திய இனிப்பு வகை.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    prepTime: 6,
    isVeg: true,
    isBestSeller: true,
  },
];

// Mock historical feedback for customer dashboard
export const initialReviews = [
  { id: '1', name: 'Karthik Raja', rating: 5, comment: 'Dose was extremely crispy. Real ghee taste!', commentTa: 'தோசை மிகவும் மொறுமொறுப்பாக இருந்தது. உண்மையான நெய் மணம்!', date: '2 hours ago' },
  { id: '2', name: 'Shalini S', rating: 5, comment: 'Ambur Biryani is authentic! Best packaging.', commentTa: 'ஆம்பூர் பிரியாணி அருமை! தரமான பேக்கிங்.', date: 'Yesterday' },
  { id: '3', name: 'Vijay Anand', rating: 4, comment: 'Degree coffee was too good, but delivery was delayed, wait prediction was correct though.', commentTa: 'டிகிரி காபி பிரமாதம், டெலிவரி கொஞ்சம் தாமதம் ஆனால் கணக்கீடு சரியாக இருந்தது.', date: '3 days ago' },
];

export const translations = {
  en: {
    appName: 'DineFlow',
    appSlogan: 'Dine, Order & Track Fluidly',
    dineIn: 'Dine-In',
    delivery: 'Delivery',
    tableNo: 'Table No.',
    searchPlaceholder: 'Search culinary delights...',
    categoriesText: 'Categories',
    bestSellers: 'Best Sellers',
    vegTag: 'Veg',
    nonVegTag: 'Non-veg',
    addBtn: 'Add to Cart',
    customizing: 'Customize',
    spiceLevel: 'Spice Level',
    mild: 'Mild',
    medium: 'Medium',
    hot: 'Hot',
    extrasText: 'Available Extras',
    addedToCart: 'Added to your plate!',
    noItems: 'Your cart is completely empty',
    subtotal: 'Subtotal',
    tax: 'Taxes & Packing (5%)',
    deliveryFee: 'Delivery Partner Fee',
    total: 'Grand Total',
    placeOrder: 'Place Order',
    orderHistory: 'My Orders',
    cart: 'Plate',
    trackOrder: 'Track Order',
    language: 'Language',
    aiRecs: 'DineFlow Smart AI Recommendations ✨',
    aiSuggest: 'AI Suggestion Based on Your Flavor Mood:',
    recommendMe: 'Recommend me something!',
    waitingTime: 'Wait Time Prediction',
    mins: 'mins',
    reviewsTitle: 'Customer Food Reviews',
    writeReview: 'Share Your Experience',
    tableOrderQR: 'QR Table Quick Ordering',
    enterTableNum: 'Enter Table Number:',
    scanSim: 'Scan / Set Table',
    paymentSuccess: 'Payment successful! Order sent to kitchen.',
    activeOrder: 'Active Order Tracking',
    statusPending: 'Waiting Kitchen Approval',
    statusPreparing: 'Chef is preparing your meal',
    statusReady: 'Ready for Pick Up / Delivery',
    statusDelivered: 'Dispatched & Delivered safely!',
    riderChat: 'Delivery Partner Chat',
    typeMessage: 'Type reply...',
    deliveryAddressText: 'Delivery Location Address:',
    customerNameText: 'Your Full Name:',
    customerPhoneText: 'Phone Number:',
    branchText: 'Select Branch:',
    adminHeadline: 'Kitchen Admin & Operations Suite',
    analyticsText: 'Revenue & Volume Live Analytics',
    orderQueue: 'Order Preparation Queue',
    updateStatus: 'Cycle Status',
    cancelOrder: 'Cancel',
    deliveryPartnerDashboard: 'Delivery Agent App',
    acceptDelivery: 'Accept Delivery Job',
    markPickedUp: 'Picked Up (Out for Delivery)',
    markDelivered: 'Dispatched / Delivered',
    jobDetails: 'Delivery Order Details',
    distanceRemaining: 'Est. Location Distance:',
    multiDeviceTitle: 'DineFlow Multi-Actor Synchronization Hub',
    switchActor: 'Switch View Role:',
    customerView: '📱 Customer Mobile App',
    kitchenView: '🖥️ Kitchen & Admin Console',
    riderView: '🛵 Delivery Companion',
    allViews: '🔗 All Devices Unified Live (Multi-Device Simulator)',
    realTimeSyncEnabled: '⚡ Live Device Sync Mode Active',
    activeOrdersLabel: 'Active Orders Running in Hub:',
    statsItems: 'Items sold',
    statsRevenue: 'Live Revenue',
    statsFeedback: 'Satisfied Rate',
  },
  ta: {
    appName: 'டைன்ஃப்ளோ',
    appSlogan: 'எளிதான முறையில் உணவை ஆர்டர் செய்து கண்காணிக்கவும்',
    dineIn: 'உள்அமர்வு (Dine-In)',
    delivery: 'வீட்டு விநியோகம்',
    tableNo: 'மேஜை எண்.',
    searchPlaceholder: 'உங்களுக்குப் பிடித்த உணவைத் தேடுக...',
    categoriesText: 'உணவு வகைகள்',
    bestSellers: 'பிரபலமான தேர்வுகள்',
    vegTag: 'சைவம்',
    nonVegTag: 'அசைவம்',
    addBtn: 'பிளேட்டில் சேர்க்க',
    customizing: 'விருப்ப தேர்வு சேர்க்க',
    spiceLevel: 'காரத்தன்மை',
    mild: 'குறைந்த காரம்',
    medium: 'நடுத்தர காரம்',
    hot: 'அதிக காரம்',
    extrasText: 'கூடுதல் விருப்பங்கள்',
    addedToCart: 'உணவு பிளேட்டில் சேர்க்கப்பட்டது!',
    noItems: 'உங்கள் பிளேட் காலியாக உள்ளது',
    subtotal: 'உணவுத் தொகை',
    tax: 'ஜிஎஸ்டி மற்றும் பேக்கிங் (5%)',
    deliveryFee: 'டெலிவரி கட்டணம்',
    total: 'மொத்தத் தொகை',
    placeOrder: 'ஆர்டர் செய்க',
    orderHistory: 'எனது முந்தைய ஆர்டர்கள்',
    cart: 'பிளேட்',
    trackOrder: 'ஆர்டரைத் தொடர்க',
    language: 'மொழி',
    aiRecs: 'டைன்ஃப்ளோ AI உணவுப் பரிந்துரைகள் ✨',
    aiSuggest: 'உங்கள் விருப்பத்திற்கு ஏற்ப AI பரிந்துரைப்பது:',
    recommendMe: 'எனக்குப் பரிந்துரை செய்!',
    waitingTime: 'காத்திருக்கும் நேரம்',
    mins: 'நிமிடங்கள்',
    reviewsTitle: 'வாடிக்கையாளர் மதிப்புரைகள்',
    writeReview: 'உங்கள் கருத்தைப் பகிரவும்',
    tableOrderQR: 'QR மேஜை விரைவு ஆர்டர்',
    enterTableNum: 'மேஜை எண்ணை உள்ளிடவும்:',
    scanSim: 'ஸ்கேன் / மேஜையை அமை',
    paymentSuccess: 'கட்டணம் செலுத்தப்பட்டது! சமையலறைக்கு அனுப்பப்பட்டது.',
    activeOrder: 'நேரடி ஆர்டர் கண்காணிப்பு',
    statusPending: 'சமையலறை ஒப்புதலுக்காகக் காத்திருக்கிறது',
    statusPreparing: 'உணவு தயாராகிக் கொண்டிருக்கிறது',
    statusReady: 'தயாராகிவிட்டது / டெலிவரிக்குத் தயார்',
    statusDelivered: 'ஆர்டர் பாதுகாப்பாக விநியோகிக்கப்பட்டது!',
    riderChat: 'டெலிவரி நண்பர் அரட்டை',
    typeMessage: 'பதில் எழுதுக...',
    deliveryAddressText: 'டெலிவரி முகவரி:',
    customerNameText: 'உங்கள் முழு பெயர்:',
    customerPhoneText: 'தொலைபேசி எண்:',
    branchText: 'கிளையைத் தேர்ந்தெடுக்கவும்:',
    adminHeadline: 'சமையலறை மற்றும் மேலாண்மை போர்டல்',
    analyticsText: 'வருவாய் மற்றும் விற்பனை நேரடி பகுப்பாய்வு',
    orderQueue: 'உள்வரும் ஆர்டர் வரிசை',
    updateStatus: 'நிலையை மாற்று',
    cancelOrder: 'ரத்து செய்க',
    deliveryPartnerDashboard: 'விநியோகப் பிரதிநிதி செயலி',
    acceptDelivery: 'விநியோக வேலையை ஏற்றுக்கொள்',
    markPickedUp: 'உணவை பெற்றுக்கொண்டேன் (வண்டியில்)',
    markDelivered: 'வழங்கப்பட்டு விட்டது (டெலிவர்ட்)',
    jobDetails: 'டெலிவரி ஆர்டர் விவரங்கள்',
    distanceRemaining: 'மீதமுள்ள தூரம்:',
    multiDeviceTitle: 'டைன்ஃப்ளோ ஆல்-இன்-ஒன் நேரடி இணைப்பு மையம்',
    switchActor: 'செயல்பாட்டைத் தேர்வு செய்க:',
    customerView: '📱 வாடிக்கையாளர் செயலி',
    kitchenView: '🖥️ சமையலறை மேலாண்மை',
    riderView: '🛵 டெலிவரி செயலி',
    allViews: '🔗 அனைத்து சாதனங்களும் ஒரே திரையில் (நேரடி இணைப்பு)',
    realTimeSyncEnabled: '⚡ நேரடி சாதன ஒத்திசைவு செயலில் உள்ளது',
    activeOrdersLabel: 'தற்போது ஓடும் ஆர்டர்கள்:',
    statsItems: 'விற்கப்பட்டவை',
    statsRevenue: 'நேரடி வருவாய்',
    statsFeedback: 'வாடிக்கையாளர் திருப்தி',
  },
};
